# Use root/example as user/password credentials
version: '3.1'
services:
  mongodb:
      image: mongo:latest
      container_name: mongodb
      hostname: mongodb
      ports:
          - "27017:27017"
  backbtg:
      container_name: backbtg
      build:
        context: ./Back/BackBTG
        dockerfile: Dockerfile
      ports:
        - "8000:8000"
      links:
        - mongodb
      depends_on:
        - mongodb
  angular-frontend:
      container_name: frontend-btg
      build:
        context: ./FrontEnd/FrontBTG
        dockerfile: Dockerfile
      ports:
        - '4200:80'


    